mappings:
  - match: .bash(\w)*
    target_os:
      - "Linux"
      - "Darwin"

modules:
  # other useful stuff
  - repo: git@github.com:tmux-plugins/tpm.git
    pull_only: true
    link: none
    location: ~/.config/tmux/plugins/tpm
    name: tpm
  - repo: git@github.com:junegunn/vim-plug.git
    pull_only: true
    link: none
    # Mapping were not reimplemented in rust as of 10.0...
    #mappings:
    #  - match: '*'
    #    skip: true
    #  - match: '\/plug.vim$'
    #    target_dir: ~/.config/vim/autoload/
    location: ~/.config/vim/autoload
    name: vim-plug
  - repo: git@github.com:zap-zsh/zap.git
    pull_only: true
    link: none
    location: ~/.local/share/zap
    name: zap
